apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat
  namespace: chat
spec:
  template:
    spec:
      containers:
        - name: chat
          image: msfintlproduseast2.azurecr.io/chatbot:latest-produseast2
          env:
            - name: ENVIRONMENT
              value: produseast2
