configMapGenerator:
  - name: chat-configmap
    namespace: chat
    files:
      - .env.produseast2
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment_patch.yml
  - target:
      kind: Ingress
      name: chat-ingress
    path: ingress_patch.json
secretGenerator:
  - name: chat-secret
    namespace: chat
    envs:
      - .env.secret.produseast2
