apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chat
  name: chat
  labels:
    app: chat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat
      azure.workload.identity/use: 'true'
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: chat
        azure.workload.identity/use: 'true'
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: ai-admin
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: chat
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: chat
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: chat
          image: msfintlnycdev1.azurecr.io/chatbot:latest-dev
          imagePullPolicy: Always
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 1
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          env:
            - name: AZURE_AD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: AZURE_AD_CLIENT_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: OPENAI_API_KEY
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: NEXTAUTH_SECRET
            - name: OPENAI_API_HOST
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: OPENAI_API_HOST
            - name: APIM_CHAT_ENDPONT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: APIM_CHAT_ENDPONT
            - name: APIM_MANAGEMENT_ENDPONT
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: APIM_MANAGEMENT_ENDPONT
            - name: OPENAI_API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: OPENAI_API_VERSION
            - name: API_HOST_DEV_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: API_HOST_DEV_PREFIX
            - name: OPENAI_API_TYPE
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: OPENAI_API_TYPE
            - name: AZURE_DEPLOYMENT_ID
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: AZURE_DEPLOYMENT_ID
            - name: API_HOST_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: API_HOST_PREFIX
            - name: DEFAULT_MODEL
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: DEFAULT_MODEL
            - name: NEXTAUTH_URL
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: NEXTAUTH_URL
            - name: AZURE_AD_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: AZURE_AD_CLIENT_ID
            - name: AZURE_AD_TENANT_ID
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: AZURE_AD_TENANT_ID
