apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-hpa
spec:
  maxReplicas: 15 # define max replica count
  minReplicas: 3  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat
  targetCPUUtilizationPercentage: 50 # target CPU utilization