apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: chat-vpa
  namespace: chat
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: chat
  updatePolicy:
    updateMode: "Auto"