configMapGenerator:
  - files:
      - config.json
    name: chat-configmap
    namespace: chat
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: deployment_patch.yml
secretGenerator:
  - name: chat-secret
    envs:
      - .env.secret.dev
