name: $(Build.BuildId)

trigger: none

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_push
    displayName: Build and Push Image
    jobs:
      - job: buildPush
        displayName: Build and Push
        steps:
          - task: Docker@2
            displayName: Build Image
            inputs:
              command: build
              repository: 'ai-platform'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: 'msfintlnycdevai'
              arguments: '--build-arg BUILD=$(Build.BuildId) --build-arg ENV=dev'
              tags: |
                latest
                $(Build.BuildId)
          - task: Docker@2
            displayName: Push Image
            inputs:
              command: push
              repository: 'ai-platform'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: 'msfintlnycdevai'
              tags: |
                latest
                $(Build.BuildId)
          - task: PublishPipelineArtifact@1
            displayName: 'Publish Source Code'
            inputs:
              targetPath: '$(Build.SourcesDirectory)'
              artifact: 'DevBuild'
              publishLocation: 'pipeline'
