stages:
  - stage: build_push
    displayName: Build and Push Image
    jobs:
        - job: buildPush
          displayName: Build and Push
          pool:
              vmImage: ubuntu-latest
          steps:
              - task: Docker@2
                displayName: Build Image
                inputs:
                    command: build
                    repository: 'chatbot'
                    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
                    containerRegistry: 'azure-cr-dev'
                    tags: latest
              - task: Docker@2
                displayName: Push Image
                inputs:
                    command: push
                    repository: 'chatbot'
                    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
                    containerRegistry: 'azure-cr-dev'
                    tags: latest
