name: ProdUSEast2 Application Deployment

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr: none

pool:
  vmImage: ubuntu-latest

resources:
  - repo: self

variables:
  - group: msfintl-nyc-produseast2-ai
  - group: nextauth-produseast2
  # Container registry service connection established during pipeline creation
  - name: dockerRegistryServiceConnection
    value: 'c4bdd380-1da8-426c-b7d5-e73ed0c95295'
  - name: k8ServiceConnection
    value: 'msfintl-nyc-produseast2-ai-chat'
  - name: imageRepository
    value: 'chatbot'
  - name: containerRegistry
    value: 'msfintlnycproduseast2.azurecr.io'
  - name: dockerfilePath
    value: '**/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'
  - name: imagePullSecret
    value: 'msfintlnycproduseast2bbf1-auth'
  - name: namespace
    value: 'chat'
  - name: env
    value: 'produseast2'
  - name: vmImageName
    value: 'ubuntu-latest'

stages:
  - template: './templates/k8-deploy.yml'
