name: $(Build.BuildId)

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: build_push
    displayName: Build and Push Image
    jobs:
      - job: buildPush
        displayName: Build and Push
        steps:
          - task: Docker@2
            displayName: Build Image
            inputs:
              command: build
              repository: 'chatbot'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: 'msfintlnycproduseast2'
              tags: |
                latest
                $(Build.BuildId)
          - task: Docker@2
            displayName: Push Image
            inputs:
              command: push
              repository: 'chatbot'
              dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
              containerRegistry: 'msfintlnycproduseast2'
              tags: |
                latest
                $(Build.BuildId)
